/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package todolistproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Blod2
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     * @param _ID user id from login form
     */
    public MainWindow(int _ID) {
        initComponents();
        uid = _ID;
        //setting models for lists, models control the list contents
       jListTodo.setModel(listModelTodo);
       jListOngoing.setModel(listModelOngoing);
       jListFinished.setModel(listModelFinished);
       
       /**TODO:
       * add procedures for add job and delete job buttons
       * make sorting by date or something else
       */
       
       dbConnect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListFinished = new javax.swing.JList<>();
        jButtonDeleteTask = new javax.swing.JButton();
        jButtonBackToOngoing = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListTodo = new javax.swing.JList<>();
        jButtonForvardToOngoing = new javax.swing.JButton();
        jButtonAddTask = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListOngoing = new javax.swing.JList<>();
        jButtonForvardToFinished = new javax.swing.JButton();
        jButtonBackToTodo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 320));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jListFinished.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jListFinished);

        jButtonDeleteTask.setText("Delete task");

        jButtonBackToOngoing.setText("Back");
        jButtonBackToOngoing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackToOngoingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButtonBackToOngoing)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                        .addComponent(jButtonDeleteTask)
                        .addGap(19, 19, 19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDeleteTask)
                    .addComponent(jButtonBackToOngoing))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jListTodo.setModel(jListOngoing.getModel());
        jScrollPane1.setViewportView(jListTodo);

        jButtonForvardToOngoing.setText("Forvard");
        jButtonForvardToOngoing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonForvardToOngoingActionPerformed(evt);
            }
        });

        jButtonAddTask.setText("Add task");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addComponent(jButtonAddTask)
                .addGap(18, 18, 18)
                .addComponent(jButtonForvardToOngoing)
                .addGap(23, 23, 23))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonForvardToOngoing)
                    .addComponent(jButtonAddTask))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jListOngoing.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListOngoing);

        jButtonForvardToFinished.setText("Forvard");
        jButtonForvardToFinished.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonForvardToFinishedActionPerformed(evt);
            }
        });

        jButtonBackToTodo.setText("Back");
        jButtonBackToTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackToTodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButtonBackToTodo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                        .addComponent(jButtonForvardToFinished)
                        .addGap(19, 19, 19))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonForvardToFinished)
                    .addComponent(jButtonBackToTodo))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jLabel1.setText("TODO list");

        jLabel2.setText("Ongoing list");

        jLabel3.setText("Finished list");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /*
    * Forvard and Back buttons just throwing data from one table
    * to another. Pretty lazy, but it works. 
    * 
    */
    
    //procedure made for optimizing code length (but as for me, it is less readable now)
    private void buttonQueryExecution(String _query, String _delquery){
        try{
           stmt.executeUpdate(_query);
           stmt.executeUpdate(_delquery);
       }
       catch(SQLException ex){
           JOptionPane.showMessageDialog(this, ex.getMessage());
       }
       dbFillLists();   
    }
    
    //Back button to ONGOING
    private void jButtonBackToOngoingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackToOngoingActionPerformed
       String selectedJob = jListFinished.getSelectedValue();

       String query = "insert into ongoing_list (user_ID, job_text, job_date)\n"
               +"select user_ID, job_text, job_date from finished_list where job_text = \""+selectedJob+"\";";
       String delquery = "delete from finished_list where job_text = \""+selectedJob+"\";";
       buttonQueryExecution(query,delquery);
    }//GEN-LAST:event_jButtonBackToOngoingActionPerformed
        
    //Forvard button to ONGOING
    private void jButtonForvardToOngoingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonForvardToOngoingActionPerformed
       
       String selectedJob = jListTodo.getSelectedValue();

       String query = "insert into ongoing_list (user_ID, job_text, job_date)\n"
               +"select user_ID, job_text, job_date from todo_list where job_text = \""+selectedJob+"\";";
       String delquery = "delete from todo_list where job_text = \""+selectedJob+"\";";
      buttonQueryExecution(query,delquery);
    }//GEN-LAST:event_jButtonForvardToOngoingActionPerformed
    
    //Back button to TODO
    private void jButtonBackToTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackToTodoActionPerformed
  
       String selectedJob = jListOngoing.getSelectedValue();

       String query = "insert into todo_list (user_ID, job_text, job_date)\n"
               +"select user_ID, job_text, job_date from ongoing_list where job_text = \""+selectedJob+"\";";
       String delquery = "delete from ongoing_list where job_text = \""+selectedJob+"\";";
       buttonQueryExecution(query,delquery);    
    }//GEN-LAST:event_jButtonBackToTodoActionPerformed
    
    //Forvard button to FINISHED
    private void jButtonForvardToFinishedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonForvardToFinishedActionPerformed
       String selectedJob = jListOngoing.getSelectedValue();

       String query = "insert into finished_list (user_ID, job_text, job_date)\n"
               +"select user_ID, job_text, job_date from ongoing_list where job_text = \""+selectedJob+"\";";
       String delquery = "delete from ongoing_list where job_text = \""+selectedJob+"\";";
       buttonQueryExecution(query,delquery); 
    }//GEN-LAST:event_jButtonForvardToFinishedActionPerformed

    //making a disconnect on window closing
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        dbDisconnect();
    }//GEN-LAST:event_formWindowClosed

    //Connecting to database, loading data into lists
    private void dbConnect(){
        
        try {
            // opening database connection to MySQL server
            con = DriverManager.getConnection(url, user, password);

            // getting Statement object to execute query
            stmt = con.createStatement();
            
            dbFillLists();
            
        } catch (SQLException sqlEx) {
           JOptionPane.showMessageDialog(this, sqlEx.getMessage());
        }
    }
    
    //Disconnect from the database
    private void dbDisconnect(){
            try { con.close(); } catch(SQLException se) { /*can't do anything */ }
            try { stmt.close(); } catch(SQLException se) { /*can't do anything */ }
            try { rs.close(); } catch(SQLException se) { /*can't do anything */ }
    }
    
    //procedure for filling and refreshing listboxes
    private void dbFillLists(){
        //TODO user_id is still fixed, need much work to do with logging
       listModelTodo.clear();
       listModelOngoing.clear();
       listModelFinished.clear();
       
       String query1 = "select job_text from todo_list\n"+"where user_id = "+uid+";";
       String query2 = "select job_text from ongoing_list\n"+"where user_id = "+uid+";";
       String query3 = "select job_text from finished_list\n"+"where user_id = "+uid+";";
            try{
       // executing SELECT query
            rs = stmt.executeQuery(query1);
            //Loading data to lists
            while (rs.next()) {
                listModelTodo.add(listModelTodo.getSize(), rs.getString(1));
            }

            rs = stmt.executeQuery(query2);
            while (rs.next()) {
                listModelOngoing.add(listModelOngoing.getSize(), rs.getString(1));
            }
            
            rs = stmt.executeQuery(query3);
            while (rs.next()) {
                listModelFinished.add(listModelFinished.getSize(), rs.getString(1));
            }
            }
            catch(SQLException ex){
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });*/
    }
       
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddTask;
    private javax.swing.JButton jButtonBackToOngoing;
    private javax.swing.JButton jButtonBackToTodo;
    private javax.swing.JButton jButtonDeleteTask;
    private javax.swing.JButton jButtonForvardToFinished;
    private javax.swing.JButton jButtonForvardToOngoing;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jListFinished;
    private javax.swing.JList<String> jListOngoing;
    private javax.swing.JList<String> jListTodo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables

    //User variables declaration @author Blod2
    final DefaultListModel listModelTodo = new DefaultListModel();
    final DefaultListModel listModelOngoing = new DefaultListModel();
    final DefaultListModel listModelFinished = new DefaultListModel();
    
        // JDBC URL, username and password of MySQL server
    private static final String url = "jdbc:mysql://localhost:3306/listbase";
    private static final String user = "root";
    private static final String password = "02021995";

        // JDBC variables for opening and managing connection
    private static Connection con;
    private static Statement stmt;
    private static ResultSet rs;
    
    private int uid;
    //End of user variables declaration
}
